#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys  
reload(sys)  
sys.setdefaultencoding('utf8')

import os
import argparse
sys.path.append(os.path.join(os.path.dirname(__file__), "pythonlib"))

from pdfcreator import Pdfcreator

def parse_args(args):
    """Get the command line arguments, and make sure they are correct."""
    args = [arg for arg in args if arg != "__ignore_me__"]

    parser = argparse.ArgumentParser()

    parser.add_argument("-o", "--output", type=str, dest="output",
                        default="", help="Output file")
    parser.add_argument("-i", "--input", type=str, dest="input",
                        default="", help="Output file")
    
    args = parser.parse_args(args[1:])

    return args

args = sys.argv
args = parse_args(args)

pdfcreator = Pdfcreator()
pdfcreator.createReport( args.input, args.output)
del pdfcreator